### ISSUE TITLE
Initial height set to 0

### ISSUE THREAD

**Issue by hermansje** [Codecademy/stuff.js#12]
When running the example in Chrome, the inner iframe height was set to 0, making the output invisible.
It became visible when I opened the devtools (on resize).
[This commit from a fork](https://github.com/quartzmo/stuff.js/commit/703d8081f84ceec2c12d8cee493d80b2c6ee4f27) solves that problem for me.
Could this be fixed here too? (I can make a pull request with the same fix if you want.)

**Comment by amasad** [comment]
PR would be great, thanks!
