### ISSUE TITLE
Dev server hangs (Node v0.10.8)

### ISSUE THREAD

**Issue by quartzmo** [Codecademy/stuff.js#9]
I had trouble running both the example (port 8080) and secure (port 8888) servers. Both appeared to hang. I got the secure server to run by adding a call to `resume()`, per the node-static readme example. Adding this call did not fix the example server for me, however.

```
require('http').createServer(function (request, response) {
  request.addListener('end', function () {
    secure.serve(request, response);
  }).resume();
}).listen(8888);
```

**Comment by amasad** [comment]
Looks like it works fine on modern node
